<?php
/**
 * Verified Elementor widget definitions.
 *
 * @package AIBuilderConnector
 */

namespace AIBC;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Stores Phase 11 widget support metadata and safe setting allowlists.
 */
final class Widget_Definition_Registry {
	public const STATUS_DETECTED     = 'detected';
	public const STATUS_ALLOWED      = 'allowed';
	public const STATUS_VERIFIED     = 'verified';
	public const STATUS_INTROSPECTED = 'introspected';
	public const STATUS_UNSUPPORTED  = 'unsupported';
	public const STATUS_NEEDS_REVIEW = 'needs_review';

	private const TESTED_ELEMENTOR_VERSIONS = array( '4.2.0' );

	/**
	 * Optional introspector for auto-detecting addon widget definitions.
	 *
	 * @var Widget_Introspector|null
	 */
	private ?Widget_Introspector $introspector;

	/**
	 * Per-request cache of introspected definitions (name => definition|false).
	 *
	 * @var array<string,array<string,mixed>|false>
	 */
	private array $introspection_cache = array();

	/**
	 * Registry constructor.
	 *
	 * @param Widget_Introspector|null $introspector Optional addon-widget introspector.
	 */
	public function __construct( ?Widget_Introspector $introspector = null ) {
		$this->introspector = $introspector;
	}

	/**
	 * Gets all verified widget definitions.
	 *
	 * @return array<string,array<string,mixed>>
	 */
	public function list_definitions(): array {
		return array(
			'container'   => $this->definition(
				'container',
				__( 'Container', 'ai-builder-connector' ),
				array(),
				array( 'content_width', 'width', 'min_height', 'flex_direction', 'justify_content', 'align_items', 'gap', 'background_background', 'background_color', 'padding', 'margin' ),
				array(
					'content_width' => 'boxed',
					'width'         => array( 'unit' => 'px', 'size' => 1200 ),
				),
				__( 'Use as a layout wrapper only; nested layout rules are validated separately.', 'ai-builder-connector' )
			),
			'heading'     => $this->definition(
				'heading',
				__( 'Heading', 'ai-builder-connector' ),
				array( 'title' ),
				array( 'title', 'header_size', 'align', 'title_color', 'typography_typography', 'typography_font_family', 'typography_font_size', 'typography_font_weight', 'typography_line_height' ),
				array(
					'title'       => __( 'Review Draft', 'ai-builder-connector' ),
					'header_size' => 'h2',
				),
				__( 'Supports safe text and basic typography only.', 'ai-builder-connector' ),
				array(
					'title'       => array( 'type' => 'text' ),
					'header_size' => array(
						'type'    => 'choice',
						'choices' => array( 'h1', 'h2', 'h3', 'h4', 'h5', 'h6' ),
					),
				)
			),
			'text-editor' => $this->definition(
				'text-editor',
				__( 'Text Editor', 'ai-builder-connector' ),
				array( 'editor' ),
				array( 'editor', 'align', 'drop_cap', 'columns', 'text_color', 'typography_typography', 'typography_font_family', 'typography_font_size', 'typography_font_weight', 'typography_line_height' ),
				array(
					'editor' => '<p>' . esc_html__( 'Draft copy for review.', 'ai-builder-connector' ) . '</p>',
				),
				__( 'HTML is limited to sanitized editor content generated by AIBC.', 'ai-builder-connector' ),
				array(
					'editor' => array( 'type' => 'rich_text' ),
				)
			),
			'image'       => $this->definition(
				'image',
				__( 'Image', 'ai-builder-connector' ),
				array( 'image' ),
				array( 'image', 'caption', 'align', 'image_size', 'width', 'border_radius' ),
				array(
					'image'      => array( 'url' => '', 'id' => '' ),
					'image_size' => 'large',
				),
				__( 'Phase 11 does not fetch or upload media; empty placeholders are allowed.', 'ai-builder-connector' ),
				array(
					'caption' => array( 'type' => 'text' ),
				)
			),
			'button'      => $this->definition(
				'button',
				__( 'Button', 'ai-builder-connector' ),
				array( 'text', 'link' ),
				array( 'text', 'link', 'align', 'size', 'selected_icon', 'icon_align', 'icon_indent', 'background_color', 'button_text_color', 'border_radius', 'typography_typography', 'typography_font_family', 'typography_font_weight' ),
				array(
					'text' => __( 'Contact Us', 'ai-builder-connector' ),
					'link' => array( 'url' => '#', 'is_external' => '', 'nofollow' => '' ),
				),
				__( 'Links default to placeholders; publishing remains disabled in this phase.', 'ai-builder-connector' ),
				array(
					'text' => array( 'type' => 'text' ),
					'link' => array( 'type' => 'link' ),
				)
			),
			'icon'        => $this->definition(
				'icon',
				__( 'Icon', 'ai-builder-connector' ),
				array( 'selected_icon' ),
				array( 'selected_icon', 'primary_color', 'secondary_color', 'size', 'align', 'view', 'shape' ),
				array(
					'selected_icon' => array( 'value' => 'fas fa-star', 'library' => 'fa-solid' ),
					'view'          => 'default',
				),
				__( 'Uses Elementor icon-library references only; no custom SVG input is accepted.', 'ai-builder-connector' )
			),
			'icon-box'    => $this->definition(
				'icon-box',
				__( 'Icon Box', 'ai-builder-connector' ),
				array( 'title_text', 'description_text', 'selected_icon' ),
				array( 'title_text', 'description_text', 'selected_icon', 'primary_color', 'secondary_color', 'position', 'title_color', 'description_color', 'title_typography_typography', 'description_typography_typography' ),
				array(
					'title_text'       => __( 'Review Feature', 'ai-builder-connector' ),
					'description_text' => __( 'Draft feature copy for review.', 'ai-builder-connector' ),
					'selected_icon'    => array( 'value' => 'fas fa-check', 'library' => 'fa-solid' ),
				),
				__( 'Supports static icon, title, and description content only.', 'ai-builder-connector' ),
				array(
					'title_text'       => array( 'type' => 'text' ),
					'description_text' => array( 'type' => 'text' ),
				)
			),
			'divider'     => $this->definition(
				'divider',
				__( 'Divider', 'ai-builder-connector' ),
				array(),
				array( 'style', 'weight', 'color', 'width', 'align', 'gap' ),
				array(
					'style'  => 'solid',
					'weight' => array( 'unit' => 'px', 'size' => 1 ),
				),
				__( 'Decorative divider settings are limited to simple style controls.', 'ai-builder-connector' )
			),
			'spacer'      => $this->definition(
				'spacer',
				__( 'Spacer', 'ai-builder-connector' ),
				array( 'space' ),
				array( 'space' ),
				array(
					'space' => array( 'unit' => 'px', 'size' => 32 ),
				),
				__( 'Spacing is capped by validator-safe generated values.', 'ai-builder-connector' )
			),
			'video'       => $this->definition(
				'video',
				__( 'Video', 'ai-builder-connector' ),
				array( 'video_type' ),
				array( 'video_type', 'youtube_url', 'vimeo_url', 'hosted_url', 'autoplay', 'play_on_mobile', 'mute', 'loop', 'controls', 'aspect_ratio' ),
				array(
					'video_type'   => 'youtube',
					'youtube_url'  => '',
					'aspect_ratio' => '169',
				),
				__( 'Phase 11 stores safe configuration only; no remote video is fetched by AIBC.', 'ai-builder-connector' ),
				array(
					'video_type'  => array(
						'type'    => 'choice',
						'choices' => array( 'youtube', 'vimeo' ),
					),
					'youtube_url' => array( 'type' => 'url' ),
					'vimeo_url'   => array( 'type' => 'url' ),
				)
			),
		);
	}

	/**
	 * Gets one widget definition.
	 *
	 * @return array<string,mixed>|null
	 */
	public function get_definition( string $widget_name ): ?array {
		$definitions = $this->list_definitions();
		$widget_name = sanitize_text_field( $widget_name );

		if ( isset( $definitions[ $widget_name ] ) ) {
			return $definitions[ $widget_name ];
		}

		return $this->introspected_definition( $widget_name );
	}

	/**
	 * Gets an auto-introspected definition for an addon widget, cached per request.
	 *
	 * Only used when a widget is not in the hand-verified pack. The allowlist and
	 * source checks that gate widget usage run independently in the validator and
	 * plan builder, so providing a definition here never bypasses permissions.
	 *
	 * @return array<string,mixed>|null
	 */
	private function introspected_definition( string $widget_name ): ?array {
		if ( null === $this->introspector ) {
			return null;
		}

		if ( array_key_exists( $widget_name, $this->introspection_cache ) ) {
			$cached = $this->introspection_cache[ $widget_name ];

			return false === $cached ? null : $cached;
		}

		$definition = $this->introspector->build_definition( $widget_name );

		$this->introspection_cache[ $widget_name ] = is_array( $definition ) ? $definition : false;

		return is_array( $definition ) ? $definition : null;
	}

	/**
	 * Gets safe supported setting keys for a widget.
	 *
	 * @return array<int,string>
	 */
	public function supported_setting_keys( string $widget_name ): array {
		$definition = $this->get_definition( $widget_name );

		return is_array( $definition ) ? (array) $definition['supported_settings'] : array();
	}

	/**
	 * Gets required setting keys for a widget.
	 *
	 * @return array<int,string>
	 */
	public function required_setting_keys( string $widget_name ): array {
		$definition = $this->get_definition( $widget_name );

		return is_array( $definition ) ? (array) $definition['required_settings'] : array();
	}

	/**
	 * Gets default settings for a widget.
	 *
	 * @return array<string,mixed>
	 */
	public function default_settings( string $widget_name ): array {
		$definition = $this->get_definition( $widget_name );

		return is_array( $definition ) ? (array) $definition['default_settings'] : array();
	}

	/**
	 * Gets AI-authorable content setting rules for a widget.
	 *
	 * @return array<string,array<string,mixed>>
	 */
	public function content_setting_rules( string $widget_name ): array {
		$definition = $this->get_definition( $widget_name );

		return is_array( $definition ) && is_array( $definition['content_settings'] ?? null ) ? $definition['content_settings'] : array();
	}

	/**
	 * Gets a public-safe definition row.
	 *
	 * @return array<string,mixed>|null
	 */
	public function public_definition( string $widget_name ): ?array {
		$definition = $this->get_definition( $widget_name );

		return is_array( $definition ) ? $this->sanitize_definition( $definition ) : null;
	}

	/**
	 * Gets public definition rows with current Elementor detection state.
	 *
	 * @param array<int,array<string,mixed>> $widgets Current resolved widgets.
	 * @return array<int,array<string,mixed>>
	 */
	public function runtime_rows( array $widgets, Permission_Manager $permission_manager ): array {
		$widget_map = $this->index_widgets( $widgets );
		$rows       = array();

		foreach ( $this->list_definitions() as $widget_name => $definition ) {
			$widget   = $widget_map[ $widget_name ] ?? null;
			if ( null === $widget && 'container' === $widget_name && ! empty( $widgets ) ) {
				$widget = array(
					'name'            => 'container',
					'title'           => __( 'Container', 'ai-builder-connector' ),
					'categories'      => array( 'layout' ),
					'class_name'      => '',
					'source_slug'     => Addon_Detector::ELEMENTOR_CORE,
					'source_name'     => __( 'Elementor Core', 'ai-builder-connector' ),
					'review_required' => false,
				);
			}

			$detected = is_array( $widget );
			$allowed  = $detected && ( 'container' === $widget_name ? $permission_manager->is_addon_allowed( Addon_Detector::ELEMENTOR_CORE ) : $permission_manager->is_widget_allowed( $widget ) );

			$row = $this->sanitize_definition( $definition );
			$row['detected']       = $detected;
			$row['allowed']        = $allowed;
			$row['runtime_status'] = $this->runtime_status( $row, $widget, $allowed );
			$row['class_name']     = is_array( $widget ) ? sanitize_text_field( (string) ( $widget['class_name'] ?? '' ) ) : '';
			$row['categories']     = is_array( $widget ) ? array_values( array_map( 'sanitize_text_field', (array) ( $widget['categories'] ?? array() ) ) ) : array();

			$rows[] = $row;
		}

		return $rows;
	}

	/**
	 * Builds one definition.
	 *
	 * @param array<int,string>   $required Required setting keys.
	 * @param array<int,string>   $supported Supported setting keys.
	 * @param array<string,mixed> $defaults Default settings.
	 * @param array<string,array<string,mixed>> $content_settings AI-authorable content rules.
	 * @return array<string,mixed>
	 */
	private function definition( string $identifier, string $title, array $required, array $supported, array $defaults, string $limitations, array $content_settings = array() ): array {
		return array(
			'identifier'              => sanitize_text_field( $identifier ),
			'title'                   => sanitize_text_field( $title ),
			'source_plugin'           => Addon_Detector::ELEMENTOR_CORE,
			'support_status'          => self::STATUS_VERIFIED,
			'required_settings'       => array_values( array_map( 'sanitize_key', $required ) ),
			'supported_settings'      => array_values( array_map( 'sanitize_key', $supported ) ),
			'default_settings'        => $defaults,
			'content_settings'        => $content_settings,
			'validation_rules'        => array(
				'registered_widget_required',
				'addon_must_be_allowed',
				'widget_must_be_allowed',
				'unsupported_settings_rejected',
				'required_settings_present',
			),
			'responsive_capabilities' => array(
				'desktop',
				'tablet',
				'mobile',
			),
			'tested_elementor_versions' => self::TESTED_ELEMENTOR_VERSIONS,
			'known_limitations'         => sanitize_text_field( $limitations ),
		);
	}

	/**
	 * Sanitizes a definition for admin and MCP responses.
	 *
	 * @param array<string,mixed> $definition Raw definition.
	 * @return array<string,mixed>
	 */
	private function sanitize_definition( array $definition ): array {
		return array(
			'identifier'                => sanitize_text_field( (string) ( $definition['identifier'] ?? '' ) ),
			'title'                     => sanitize_text_field( (string) ( $definition['title'] ?? '' ) ),
			'source_plugin'             => sanitize_key( (string) ( $definition['source_plugin'] ?? '' ) ),
			'support_status'            => sanitize_key( (string) ( $definition['support_status'] ?? self::STATUS_UNSUPPORTED ) ),
			'required_settings'         => array_values( array_map( 'sanitize_key', (array) ( $definition['required_settings'] ?? array() ) ) ),
			'supported_settings'        => array_values( array_map( 'sanitize_key', (array) ( $definition['supported_settings'] ?? array() ) ) ),
			'default_settings'          => $definition['default_settings'] ?? array(),
			'ai_content_settings'       => $this->sanitize_content_settings( (array) ( $definition['content_settings'] ?? array() ) ),
			'validation_rules'          => array_values( array_map( 'sanitize_key', (array) ( $definition['validation_rules'] ?? array() ) ) ),
			'responsive_capabilities'   => array_values( array_map( 'sanitize_key', (array) ( $definition['responsive_capabilities'] ?? array() ) ) ),
			'tested_elementor_versions' => array_values( array_map( 'sanitize_text_field', (array) ( $definition['tested_elementor_versions'] ?? array() ) ) ),
			'known_limitations'         => sanitize_text_field( (string) ( $definition['known_limitations'] ?? '' ) ),
		);
	}

	/**
	 * Sanitizes content setting rules for public responses.
	 *
	 * @param array<string,mixed> $content_settings Raw content rules.
	 * @return array<string,array<string,mixed>>
	 */
	private function sanitize_content_settings( array $content_settings ): array {
		$sanitized = array();

		foreach ( $content_settings as $key => $rule ) {
			$key = sanitize_key( (string) $key );

			if ( '' === $key || ! is_array( $rule ) ) {
				continue;
			}

			$row = array( 'type' => sanitize_key( (string) ( $rule['type'] ?? '' ) ) );

			if ( isset( $rule['choices'] ) && is_array( $rule['choices'] ) ) {
				$row['choices'] = array_values( array_map( 'sanitize_text_field', array_map( 'strval', $rule['choices'] ) ) );
			}

			$sanitized[ $key ] = $row;
		}

		return $sanitized;
	}

	/**
	 * Gets runtime status for a definition row.
	 *
	 * @param array<string,mixed>      $definition Public definition row.
	 * @param array<string,mixed>|null $widget Runtime widget row.
	 */
	private function runtime_status( array $definition, ?array $widget, bool $allowed ): string {
		if ( null === $widget ) {
			return self::STATUS_UNSUPPORTED;
		}

		if ( ! empty( $widget['review_required'] ) ) {
			return self::STATUS_NEEDS_REVIEW;
		}

		if ( self::STATUS_VERIFIED === (string) ( $definition['support_status'] ?? '' ) && $allowed ) {
			return self::STATUS_VERIFIED;
		}

		if ( $allowed ) {
			return self::STATUS_ALLOWED;
		}

		return self::STATUS_DETECTED;
	}

	/**
	 * Indexes runtime widgets by internal name.
	 *
	 * @param array<int,array<string,mixed>> $widgets Runtime widget rows.
	 * @return array<string,array<string,mixed>>
	 */
	private function index_widgets( array $widgets ): array {
		$map = array();

		foreach ( $widgets as $widget ) {
			$name = sanitize_text_field( (string) ( $widget['name'] ?? '' ) );

			if ( '' !== $name ) {
				$map[ $name ] = $widget;
			}
		}

		return $map;
	}
}
